<ul class="contact">
<li><img src="../img/ask/chat.png">
<span jid='bentleylibraryservices@chat.libraryh3lp.com' class='libraryh3lp'><a href='#' onclick='window.open("https://libraryh3lp.com/chat/bentleylibraryservices@chat.libraryh3lp.com?skin=16506&amp;identity=Library%20Services", "chat", "resizable=1,width=200,height=250"); return false;'>Chat with us</a></span></li>
<li><img src="../img/ask/email.png"><a href="mailto:libraryservices@bentley.edu">libraryservices@bentley.edu</a></li>
<li><img src="../img/ask/phone.png">781.891.2168</li>
</ul>
