		<div id="footer">
			<section class="center">				<div class="footerleft">
            <img src="../img/Logoonly.png" width="72" height="100"  style="float:left; margin-right:10px;">	
                <h3>Bentley University Library</h3>
                <ul class="footer">
<li>175 Forest Street</li>
                <li>Waltham, MA 02452 USA</li>
                <li>781.891.2231</li>
                <li><a href="mailto:library@bentley.edu">library@bentley.edu</a></li>
                </ul><br/>
                <div class="footerlinks">
                	<a href="http://www.bentley.edu/privacy">Privacy</a>
                    <a href="../about/sitemap.asp">Sitemap</a>
                    <a href="../services/suggestapurchase.asp">Suggest a Purchase</a>
                    <a href="../services/reportaproblem.asp">Report a Problem</a>
                </div>
                </div>
				<div class="footerright">
                <h3>Be Informed</h3>
                <ul class="footer">
                <li><a href="http://blogs.bentley.edu/intheknow/">In the Know - News & Events</a></li>
                <li><a href="http://blogs.bentley.edu/bookbuzz/">BookBuzz - Book Reviews</a></li>
                <li><a href="http://blogs.bentley.edu/14days/">14 Days to Have your Say</a></li>
                </ul>
<br/><div id="socialmedia">   
            
                <a href="https://www.facebook.com/bentleylibrary"><img src="../img/socialmedia/facebook.png" alt="Facebook" class="socialmedia" /></a>
                <a href="http://twitter.com/bentleylibrary"><img src="../img/socialmedia/twitter.png" alt="Twitter" class="socialmedia" /></a>
                <a href="http://pinterest.com/bentleylibrary/"><img src="../img/socialmedia/pinterest.png" alt="Pinterest" class="socialmedia" /></a></div><br/>
                <div class="footerlinks">
                <a href="https://blackboard.bentley.edu/webapps/login/">Blackboard</a>
                <a href="http://my.bentley.edu">MyBentley</a>
                <a href="http://bentley.edu">Bentley</a></div>
                </div>
	        </section>
            </div>
        </div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34405782-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
