	<div id="pagewidth">
		<header id="banner">
					<div class="center">
                    	<div class="headertower">
                        <img src="http://library.bentley.edu/img/tower.png" />
                        </div>
						<div class="headerlogo">
                        <h1><a href="../index.asp">BENTLEY LIBRARY</a></h1>
                        </div>
					<!--#include file="../includes/calendar/webevent.html" -->
			</div>
		</header>