		<div id="navigation">
			<nav class="columns center">
<div class="megamenu_container"><!-- Begin Mega Menu Container -->


    
    <ul class="megamenu"><!-- Begin Mega Menu -->
       
    
    
        <li><span class="nodrop"><a href="../index.asp">Home</a></span></li><!-- Begin Item -->
           
    
    
        <li style="left:auto;"><span class="drop">Research</span><!-- Begin Item -->
        
        
            <div class="megamenu_fullwidth drop6columns"><!-- Begin Item Container -->
            

                <div class="col_3">
                    <h5>Search</h5>
                    <ul>
                        <li><a href="../research/databasesaz.asp">Databases A-Z</a></li>
                        <li><a href="../research/subjects.asp">Databases by Subject</a></li>
                        <li><a href="../research/booksdvdsaudio.asp">Books, DVDs, Audio</a></li>
                        <li><a href="../research/filmsondemand.asp">Films on Demand</a></li>
                        <li><a href="../research/journalsmagazines.asp">Journals/Magazines</a></li>
                        <li><a href="../research/ebooks.asp">eBooks</a></li>
<!--                        <li><a href="http://ezp.bentley.edu/OverDrive/bentleyu" target="_blank">Downloadable Books/Overdrive <img src="../img/externalwindow.png" class="menuexternal" /></a></li>-->
                        <li style="color: #333;">Course Reserves: <a href="../research/coursereserves.asp">Students</a> | <a href="../research/coursereservesfaculty.asp">Faculty</a></li>
                        <li><a href="../research/news.asp">Newspapers</a></li>
                    </ul>   <br/>
                    <h4 class="standalone"><a href="../research/askalibrarian.asp" class="standalone">Ask a Librarian!</a></h4>
                </div>
                              
                <div class="col_3">
                    <h5>Beyond Bentley</h5>
                    <ul>
                        <li><a href="../research/borrowingprivileges.asp">Borrowing Privileges</a></li>
                        <li><a href="../research/interlibraryloan.asp">Interlibrary Loan</a></li>
                        <li><a href="http://scholar.google.com.ezp.bentley.edu/schhp?hl=en&lr=" target="_blank">Google Scholar <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                        <li><a href="http://www.worldcat.org/" target="_blank">WorldCat <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                    </ul>   
                    <h5>Tools</h5>
                    <ul>
                        <li><a href="http://libguides.bentley.edu/">Research Guides</a></li>
                        <li><a href="http://libguides.bentley.edu/content.php?pid=47900" target="_blank">Citing Sources <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                        <li><a href="http://libguides.bentley.edu/content.php?pid=41854&sid=308025" target="_blank">RefWorks <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                        <li><a href="http://libguides.bentley.edu/content.php?pid=41854&sid=308025" target="_blank">EndNote <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                        <li><a href="http://libguides.bentley.edu/content.php?pid=226658" target="_blank">Copyright Guidelines <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                    </ul>   
                </div>
			
                            
            </div><!-- End Item Container -->

        
        </li><!-- End Item -->
       
    
    
        <li><span class="drop">Services</span><!-- Begin Item -->
        
        
            <div class="megamenu_fullwidth drop6columns"><!-- Begin Item Container -->
            
                <div class="col_3">
                    <h5>Library Services</h5>
                    <ul>
                        <li><a href="../services/museumpasses.asp">Museum Passes</a></li>
                        <li><a href="../services/offcampusaccess.asp">Off-campus Access to eResources</a></li>
                        <li><a href="../services/loanperiodsfines.asp">Loan Periods & Fines</a></li>
                        <li><a href="../services/printingcopyingfaxingscanning.asp">Printing, Copying, Faxing, Scanning</a></li>
                        <li><a href="../services/servicesforfaculty.asp">Services for Faculty</a></li>
                        <li><a href="../services/scanondemand.asp">Scan on Demand</a></li>
						<li><a href="../services/lostandfound.asp">Lost & Found</a></li>
						<li><a href="../services/suggestapurchase.asp">Suggest a Purchase</a></li>
                        <li><a href="../services/archives.asp">Archives</a></li>
                    </ul>
                </div>
                              
                <div class="col_3">
                    <h5>My Library Account</h5>
                    <ul>
                        <li><a href="https://libcat.bentley.edu/patroninfo~S0">Renew Books</a></li>
                        <li><a href="https://interlibraryloan.bentley.edu/illiad/logon.html">Interlibrary Loan Account</a></li>
                    <li><a href="../services/librarycard.asp">Library Card</a></li>
                    </ul>   
                    <h5>Other Borrowers</h5>
                    <ul>
                        <li><a href="../services/otherborrowers.asp">Waltham Residents<br/>Bentley Retirees<br/>Alumni<br/>Visiting Faculty/Researchers</a></li>
                    </ul>   
                </div>
			
                            
            </div><!-- End Item Container -->

        
        </li><!-- End Item -->
       
    
    
        <li><span class="drop">Inside the Library</span><!-- Begin Item -->
        
        
            <div class="megamenu_fullwidth drop7columns"><!-- Begin Item Container -->
            
                <div class="col_4">
                    <h5>Rooms</h5>
                    <ul>
                        <li><a onClick="return true" href="../insidethelibrary/groupstudyrooms.asp">Group Study Rooms</a></li>
                        <li><a href="../insidethelibrary/researchinstructioncenter.asp">Research Instruction Center</a></li>
                        <li><a href="../insidethelibrary/bowlesroom.asp">Bowles Room</a></li>
                        <li><a href="../insidethelibrary/videopreviewmicroforms.asp">Video Preview/Microforms</a></li>
                        <li><a href="../insidethelibrary/phdsuites.asp">PhD Suites</a></li>
                    </ul>
                    <h5>IT Client Services</h5>
                    <ul>
                        <li><a href="../insidethelibrary/printing.asp">Printing</a></li>
                        <li><a href="../insidethelibrary/helpdesk.asp">Help Desk</a></li>
                    </ul>
   <br/>
                    <h4 class="standalone"><a href="../insidethelibrary/helpkeepthelibraryquiet.asp" class="standalone">Help Keep the Library Quiet!</a></h4>                </div>
                              
                <div class="col_3">
                    <h5>Spaces</h5>
                    <ul>
                        <li><a href="../insidethelibrary/deloittecafe.asp">Deloitte Café/Einstein’s</a></li>
                        <li><a href="../insidethelibrary/artgallery.asp">The McGladrey Art Gallery</a></li>
                        <li><a href="../insidethelibrary/cellphonebooths.asp">Cell Phone Booths</a></li>
                        <li><a href="../insidethelibrary/vendingmachines.asp">Vending Machines</a></li>
                        <li><a href="../insidethelibrary/studentlockers.asp">Student Lockers</a></li>
                        <li><a href="../insidethelibrary/graduatecarrels.asp">Graduate Carrels</a></li>
                    </ul>   
                    <h5>Centers</h5>
                    <ul>
                        <li><a href="http://academics.bentley.edu/departments/english/english-speakers-other-languages" target="_blank">ESOL <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                        <li><a href="http://academics.bentley.edu/departments/english/writing-center" target="_blank">Writing Center <img src="../img/externalwindow.png" class="menuexternal" /></a></li>
                    </ul>   
                </div>
			
                            
            </div><!-- End Item Container -->

        
        </li><!-- End Item -->
       
    
    
        <li><span class="drop">About</span><!-- Begin Item -->
        
        
            <div class="megamenu_fullwidth drop2columns"><!-- Begin Item Container -->
            

                <div class="col_3">
                    <ul>
                        <li><a href="../about/history.asp">History</a></li>
                        <li><a href="../about/staff.asp">Staff Directory</a></li>
                        <li><a href="../about/hours.asp">Hours</a></li>
                        <li><a href="../about/directionsdirectory.asp">Directions & Directory</a></li>
                        <li><a href="../about/sitemap.asp">Sitemap</a></li>
                    </ul>   
                </div>                            
			
                            
            </div><!-- End Item Container -->

        
        </li><!-- End Item -->
        
        
        
        <li class="right"><span class="nodrop"><a href="../contact/index.asp">Contact</a></span> </li>
        
        
        


    </ul><!-- End Mega Menu -->



</div><!-- End Mega Menu Container -->

	        </nav>
            </div>